
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: title
        # Do not merge when it is marked work in progress (WIP)
        must_exclude:
          regex: ^\[WIP\]
          message: This is work in progress. Do not merge yet.
        # Enforce semantic release convention.
        must_include:
          regex: ^(feat|docs|chore|fix|refactor|test|style|perf)(\(\w+\))?:.+$
          message: Semantic release conventions must be followed.
        # All todo check boxes must be checked.
      - do: description
        must_exclude:
          regex: \[ \]
          message: There are incomplete TODO task(s) unchecked.
      - do: approvals
        min:
          count: 1
        or: 
          - required:
            reviewers: [ 'saad-mo' ] 
          - required:
            reviewers: [ 'InnaAtanasova' ] 