version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: title
        begins_with:
          match: ['fix:', 'feat:', 'docs:', 'chore:']
    fail:
      - do: comment
        payload:
          body: >
            The following problems were found with this issue:
              - Title must begin with `fix:`, `feat:`, `docs:`, or `chore:`
    