version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: approvals
        or: 
          - required:
            reviewers: [ 'saad-mo' ] 
          - required:
            reviewers: [ 'InnaAtanasova' ] 