version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: approvals
        min:
          count: 2
        or: 
          - required:
            reviewers: [ saad-mo ] 
          - required:
            reviewers: [ InnaAtanasova ] 