rules:
  block-closing-brace-empty-line-before: never
  block-no-empty: true
  block-opening-brace-space-before: always
  color-no-invalid-hex: true
  #declaration-bang-space-before: always
  declaration-block-trailing-semicolon: always
  declaration-colon-space-after: always
  declaration-colon-space-before: never
  #declaration-property-value-blacklist: [ { '/^outline$/': 'none' }]
  font-family-no-duplicate-names: true
  #indentation: 4
  keyframe-declaration-no-important: true
  length-zero-no-unit: true
  max-empty-lines: 2
  #no-duplicate-selectors: true
  no-empty-source: true
  no-eol-whitespace: true
  no-extra-semicolons: true
  number-leading-zero: always
  number-no-trailing-zeros: true
  property-case: lower
  selector-list-comma-space-after: always-single-line
  selector-list-comma-space-before: never
  selector-pseudo-class-no-unknown: true
  selector-pseudo-element-case: lower
  selector-pseudo-element-colon-notation: double
  string-no-newline: true
  unit-case: lower
  unit-no-unknown: true