# master ruleset availabe here
# https://stylelint.io/user-guide/rules/

plugins: stylelint-scss
rules:
  # Possible errors
  property-no-unknown: true
  ## Color
  color-no-invalid-hex: true
  
  ## Font family
  font-family-no-duplicate-names: true

  ## String
  string-no-newline: true
  
  ## Unit
  unit-no-unknown: true
  
  ## Keyframe declaration
  keyframe-declaration-no-important: true

  ## Block
  block-no-empty: true

  ## Selector
  selector-pseudo-class-no-unknown: true

  ## General / Sheet
  no-duplicate-selectors: true
  no-empty-source: true
  no-extra-semicolons: true


  # Limit language features

  ## Declaration
  #declaration-property-value-blacklist: [ { '/^outline$/': 'none' }]


  # Stylistic issues

  ## Number
  number-no-trailing-zeros: true

  ## Length
  length-zero-no-unit: true

  ## Unit
  unit-case: lower

  ## Value

  ## Value list
  max-empty-lines: 2

  ## Property
  property-case: lower

  ## Declaration
  declaration-bang-space-before: always
  declaration-colon-space-after: always
  declaration-colon-space-before: never

  ## Declaration block
  declaration-block-trailing-semicolon: always

  ## Block
  block-closing-brace-empty-line-before: never
  block-opening-brace-space-before: always

  ## Selector
  selector-pseudo-element-case: lower
  selector-pseudo-element-colon-notation: double

  ## Selector list
  selector-list-comma-space-after: always-single-line
  selector-list-comma-space-before: never

  ## General / Sheet
  #indentation: 4
  no-eol-whitespace: true

  # stylelint-scss
  ## Rules

  ### `@`-else
  scss/at-else-closing-brace-newline-after: always-last-in-chain
  scss/at-else-closing-brace-space-after: always-intermediate
  scss/at-else-empty-line-before: never
  scss/at-else-if-parentheses-space-before: always

  ### `@`-extend
  #scss/at-extend-no-missing-placeholder: true

  ### `@`-function
  #scss/at-function-named-arguments: never
  scss/at-function-parentheses-space-before: never
  # scss/at-function-pattern: 

  ### `@`-if
  scss/at-if-closing-brace-newline-after: always-last-in-chain
  scss/at-if-closing-brace-space-after: always-intermediate

  ### `@`-import
  scss/at-import-no-partial-leading-underscore: true
  # scss/at-import-partial-extension-blacklist: 
  # scss/at-import-partial-extension-whitelist: 

  ### `@`-mixin
  scss/at-mixin-argumentless-call-parentheses: always  
  #scss/at-mixin-named-arguments: never 
  scss/at-mixin-parentheses-space-before: never
  # scss/at-mixin-pattern: 

  ### `@`-rule
  scss/at-rule-no-unknown: true

  ### `$`-variable
  #scss/dollar-variable-colon-newline-after: always-multi-line
  scss/dollar-variable-colon-space-after: always
  scss/dollar-variable-colon-space-before: never
  # scss/dollar-variable-default: true
  # scss/dollar-variable-empty-line-before: always
  scss/dollar-variable-no-missing-interpolation: true
  # scss/dollar-variable-pattern: 

  ### `%`-placeholder
  # scss/percent-placeholder-pattern: 

  ### `//`-comment
  #scss/double-slash-comment-empty-line-before: always
  #scss/double-slash-comment-inline: always
  #scss/double-slash-comment-whitespace-inside: always

  ### Declaration
  scss/declaration-nested-properties: never
  scss/declaration-nested-properties-no-divided-groups: true

  ### Media feature
  #scss/media-feature-value-dollar-variable: always

  ### Operator
  scss/operator-no-newline-after: true
  scss/operator-no-newline-before: true
  #scss/operator-no-unspaced: true

  ### Partial
  #scss/partial-no-import: true

  ### Selector
  #scss/selector-nest-combinators: always
  #scss/selector-no-redundant-nesting-selector: true

  ### General / Sheet
  #scss/no-dollar-variables: true
  #scss/no-duplicate-dollar-variables: true 