[build]
  publish = "dist/fundamental"
  command = "mkdir -p dist/fundamental/assets/images && cp src/index.html dist/fundamental/ && cp src/assets/images/headerlogo.webp dist/fundamental/assets/images/"

[context.production]
  command = "mkdir -p dist/fundamental/assets/images && cp src/index.html dist/fundamental/ && cp src/assets/images/headerlogo.webp dist/fundamental/assets/images/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"
