name: GH Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Build
        run: |
          mkdir -p dist/fundamental/assets/images
          cp src/index.html dist/fundamental/
          cp src/assets/images/headerlogo.webp dist/fundamental/assets/images/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/fundamental

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
